---
  # Update/upgrade packages.
  # Install nodejs, npm, and pm2.
  
- name: Creates Directory
  become: yes
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Copy backend dist files web server
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
    
- name: Extract backend files
  become: yes
  shell: |
   # cd ~/backend
    tar -vxf artifact.tar.gz
    pwd
    
#- name: "update apt package."
#  become: yes
#  apt:
#    update_cache: yes
 
#- name: "update packages"
#  become: yes
#  apt:
#    upgrade: yes
    
#- name: "Remove dependencies that are no longer required"
#  become: yes
 # apt:
 #   autoremove: yes   
   
    
- name: "Install Dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Executing node
  shell: |
    echo "trying to change the directory to backend"
    cd backend
    echo "current driectory now is"
    pwd
    echo "doing npm install, then npm run and npm build"
    npm install
    npm run build
    echo "stopping default pm2 nodes"
    pm2 stop default
    echo "starting backend pm2 node"
    pm2 start npm --name "backend" -- run start
    echo "checking pm2 status"
    pm2 status
    echo "changing to dist"
    cd dist
    echo "now the current working directory is "
    pwd
    echo "starting pm2 main.js"
    pm2 start main.js --update-env
    echo "checking if pm2 started successfully for main.js or not"
    pm2 status
